package image

const (
	IMAGE_FORMAT_1555  = 14
	IMAGE_FORMAT_4444  = 15
	IMAGE_FORMAT_8888  = 16
	IMAGE_FORMAT_LINK  = 17
	IMAGE_FORMAT_DXT_1 = 18
	IMAGE_FORMAT_DXT_3 = 19
	IMAGE_FORMAT_DXT_5 = 20
)

var IMAGE_FORMATS_RAW = []int{
	IMAGE_FORMAT_1555,
	IMAGE_FORMAT_4444,
	IMAGE_FORMAT_8888,
}

var IMAGE_FORMATS_DDS = []int{
	IMAGE_FORMAT_DXT_1,
	IMAGE_FORMAT_DXT_3,
	IMAGE_FORMAT_DXT_5,
}

var IMAGE_FORMATS_ALL = []int{
	IMAGE_FORMAT_LINK,
}

func init() {
	IMAGE_FORMATS_ALL = append(IMAGE_FORMATS_ALL, IMAGE_FORMATS_RAW...)
	IMAGE_FORMATS_ALL = append(IMAGE_FORMATS_ALL, IMAGE_FORMATS_DDS...)
}

const (
	IMAGE_EXTRA_NONE        = 5
	IMAGE_EXTRA_ZLIB        = 6
	IMAGE_EXTRA_ZLIB_SPRITE = 7
)

var PIX_SIZE = map[int32]int32{
	IMAGE_FORMAT_1555:  2,
	IMAGE_FORMAT_4444:  2,
	IMAGE_FORMAT_8888:  4,
	IMAGE_FORMAT_DXT_1: 2,
	IMAGE_FORMAT_DXT_3: 2,
	IMAGE_FORMAT_DXT_5: 4,
}
